export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN'
}

export enum IssuePriority {
  LOW = 'נמוכה',
  MEDIUM = 'בינונית',
  HIGH = 'גבוהה',
  CRITICAL = 'קריטית'
}

export enum IssueCategory {
  UI_UX = 'ממשק משתמש',
  BUG = 'באג טכני',
  PERFORMANCE = 'ביצועים',
  DATA = 'נתונים',
  OTHER = 'אחר'
}

export interface Attachment {
  name: string;
  type: string;
  data: string; // Base64 string for local storage demo
}

export interface Issue {
  id: string;
  description: string;
  summary: string; // Generated by AI
  priority: IssuePriority; // Generated by AI
  category: IssueCategory; // Generated by AI
  status: 'open' | 'in_progress' | 'transferred' | 'closed';
  createdAt: number;
  // New fields for Control Report
  username?: string;
  userRole?: string;
  treatmentNotes?: string;
  attachments?: Attachment[];
}

export interface KnowledgeItem {
  id: string;
  title: string;
  content: string;
  createdAt: number;
  sourceType?: 'manual' | 'file';
  fileName?: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  suggestions?: string[]; // Optional suggestions/did-you-mean list
  timestamp: number;
}

export interface QAResponse {
  answer: string;
  suggestions: string[];
}

export interface AiAnalysisResult {
  summary: string;
  priority: IssuePriority;
  category: IssueCategory;
}

export interface UserQuery {
  id: string;
  username: string;
  department?: string;
  question: string;
  answer: string;
  timestamp: number;
  isAnswered: boolean;
}

export interface QueryTrend {
  topic: string;
  count: number;
  exampleQuestions: string[];
}